### ISSUE TITLE
Add labels to events

### ISSUE THREAD

**Issue by leereilly** [morrisjs/morris.js#124]
**Friendly feature request:** I'd like to be able to attach labels to events. If I have more than a couple on a linegraph - it's hard to tell what they're for.

```javascript
Morris.Line({
  element: 'graph',
  data: weekly_data,
  xkey: 'dem-numbers',
  ykeys: ['new', 'updated'],
  labels: ['New', 'Updated'],
  events: [
    '2012-12-25' // <---- I'd like to give this a label
  ]
});
```

Cheers,
  Lee :beers:

**Comment by mkkmail** [comment]
Hi . thanks @MaZderMind 
how can use Html in lable.
JS Bin: http://jsbin.com/cavodohujo/edit?html,js,output
