### ISSUE TITLE
Clickable / Link chart regions.

### ISSUE THREAD

**Issue by oller** [morrisjs/morris.js#127]
Friendly feature request, as it doesn't look currently supported.

The optional ability to set each chart segment area to be clickable and thus link, perhaps declared optionally when the graph is created. 

I suppose, this wouldn't necessarily have to be a url, it could be a function too, allowing the graph to drill down into subsets of data etc.

```
// dead simple donut charts
Morris.Donut({
  element: 'sales',
  data: [
    {label: "Download Sales", value: 12, click: "download.html"},
    {label: "In-Store Sales", value: 30, click: "drawInStore()"},
    {label: "Mail-Order Sales", value: 20, click: "mailorder.html"}
  ]
});
```

As far as I can tell, there's no quick botch for this, as the `<path>` elements have no identifiable attributes I could use to target.

Any thoughts?

**Comment by msnpr567** [comment]
hi ... bramastana....
did u get bar chart details with above click event?? like percentage or name of each bar.

**Comment by JelteF** [comment]
Yes, the callback takes a couple of arguments.

**Comment by msnpr567** [comment]
Can you wirte an example here.

**Comment by JelteF** [comment]
check out this example: https://github.com/morrisjs/morris.js/blob/master/examples/bar.html
