### ISSUE TITLE
Uncaught Error: Graph container element not found 

### ISSUE THREAD

**Issue by bcackerman** [morrisjs/morris.js#137]
I'm getting this error even when I put something basic like:

http://pastie.org/5515931

In my code.   Is there a bug in Morris?

**Comment by eluizbr** [comment]
not works for me... any tip?

**Comment by mzamek** [comment]
are you at all using morris graphs? If not comment out these two lines:
<script src="../bower_components/morrisjs/morris.min.js"></script>
<script src="../js/morris-data.js"></script>

**Comment by ajithsimon** [comment]
Thank you tiraeth, Works for me.. 💯

**Comment by jakesylvestre** [comment]
How does one go about solving this with something like angular where you can't just move the scripts

**Comment by iamgenesisivan** [comment]
Thanks bru tiraeth, it works in my project!

**Comment by mia888** [comment]
help me

**Comment by majinliang123** [comment]
i use angularjs so it doesn't work for me after i put js after div. i think it is because i used ng-include in it

**Comment by edilsonvilarinho** [comment]
I need help
[img](https://drive.google.com/file/d/1Q3gZR66eQdaegc_h7oZdD6mZn5qeRaUc/view?usp=sharing)

Uncaught Error: Graph container element not found
    at d [as constructor] (morris.min.js:6)
    at d.c [as constructor] (morris.min.js:6)
    at new d (morris.min.js:6)
    at HTMLDocument.<anonymous> (dashboard.js:129)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)

[import scripts](https://drive.google.com/file/d/14IuMj8w3d_ElvOjNpUrMoZsUvM9B-DQY/view?usp=sharing)

**Comment by ghost** [comment]
In Angular 5 problem..How can i fix this error??

Error: Graph container element not found
morris.min.js:6:1340
d
http://localhost:3000/assets/vendor/morrisjs/morris.min.js:6:1340
c
http://localhost:3000/assets/vendor/morrisjs/morris.min.js:6:13489
d
http://localhost:3000/assets/vendor/morrisjs/morris.min.js:6:23568
d
http://localhost:3000/assets/vendor/morrisjs/morris.min.js:6:23613
<anonymous>
http://localhost:3000/assets/data/morris-data.js:3:5
j
http://localhost:3000/assets/vendor/jquery/jquery.min.js:2:29566
g/</k<
http://localhost:3000/assets/vendor/jquery/jquery.min.js:2:29882
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask
zone.js:421
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.runTask
zone.js:188
./node_modules/zone.js/dist/zone.js/</</ZoneTask.invokeTask
zone.js:496
ZoneTask/this.invoke
zone.js:485
timer
zone.js:2054

**Comment by jerinho** [comment]
> I'm getting this error even when I put something basic like:
> 
> http://pastie.org/5515931
> 
> In my code. Is there a bug in Morris?

![image](https://user-images.githubusercontent.com/706506/56075872-e57f2400-5dfb-11e9-87c3-3d2d0b7c7cbb.png)

sir. please kindly copy and paste your code here so everyone including me can see it

**Comment by noisetech** [comment]
Help me in the moment iam running templates has this  .
Uncaught Error: Graph container element not found
    at d [as constructor] (morris.min.js:6)
    at d.c [as constructor] (morris.min.js:6)
    at new d (morris.min.js:6)
    at HTMLDocument.<anonymous> (dashboard.js:129)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)

**Comment by pierresh** [comment]
This means that there is no HTML **div** having the _id_ that you defined for your Morris chart in '_element_'.
