### ISSUE TITLE
Add fillAreaColors option

### ISSUE THREAD

**Issue by Radagaisus** [morrisjs/morris.js#161]
Add an option to change the Area Charts fill color. Currently it's a slightly brighter version of the line color, but people might want to change it. (I did, wanted a brighter color there).

``` coffee
fillForSeries: (i) ->
    fill_color = @options.fillAreaColors[i]
    return fill_color if fill_color

    color = Raphael.rgb2hsl @colorFor(@data[i], i, 'line')
    Raphael.hsl(
      color.h,
      Math.min(255, color.s * 0.75),
      Math.min(255, color.l * 1.25))
```

**Comment by nerde** [comment]
👍 
I know I'm too late for the party, but couldn't you just add this? It's very useful.
