### ISSUE TITLE
Round Y-Axis numbers to a Nicer Format

### ISSUE THREAD

**Issue by Radagaisus** [morrisjs/morris.js#162]
Hi,

So my area chart looks like this:

![Screen Shot 2013-01-17 at 07 29 57](https://f.cloud.github.com/assets/550061/73886/f6bafcd8-6066-11e2-9ab3-025252d82c7f.png)

But the axis numbers are not round and nice numbers people like to see, like 250 and 500. We can tweak this behaviour.

**Comment by bilaalshah** [comment]
Can i have created this kind of graph 


(https://user-images.githubusercontent.com/5277834/36530130-15de79fa-17dc-11e8-8815-410bd03fe851.jpeg)



But i want to remove the colored area and to be shown like this

https://web.whatsapp.com/1c0c1fa7-78d2-4b20-bc80-8afe74489fc0
![whatsapp image 2018-02-20 at 6 50 36 pm](https://user-images.githubusercontent.com/5277834/36530151-232df694-17dc-11e8-9bec-ee106953696b.jpeg)
