### ISSUE TITLE
Click events

### ISSUE THREAD

**Issue by oesmith** [morrisjs/morris.js#172]
There's clearly demand for click events, so I'm merging the discussions here.

**Comment by msnpr567** [comment]
hello... its working fine...... how can i get that data on view , other than alert ,
I want show bar chart data on view for each bar . can u show solution

**Comment by JelteF** [comment]
I'm really unsure what you mean

**Comment by msnpr567** [comment]
return new Morris.Bar(options).on('click', function(i, row){
                  alert("percentage:" +row);
              });
Here alert is woking fine. but i want to display row object in view by clicking on each bar. have u understand now? Thanks for rply

**Comment by JelteF** [comment]
This is not built in, but you should just do something with the data in the row object.

**Comment by msnpr567** [comment]
Im also lokking for that "something" only,... i place that object in $rootScope variable , but its not identifing at the time on click.

**Comment by bayarmanlai** [comment]
I have bar chart with multiple series. I want to know which of them were clicked?
I mean https://github.com/morrisjs/morris.js/blob/master/examples/area.html has y and z series.

Thanks in advance
