### ISSUE TITLE
Disable data ordering when rendering a donut chart

### ISSUE THREAD

**Issue by ebiasini** [morrisjs/morris.js#200]
Hi, I would like the default data to be shown in the order in which it has been specified in the js call…

I have the following

var perc = $('div#donut').text();
var perc = parseInt(perc,10);
var perc2 = 100.00 - perc;

Morris.Donut({
  element: 'donut',
  data: [
    {label: "Label AAA", value: perc},
    {label: "Label BBB", value: perc2},
  ],
  colors: ['#D58025','#37619d'],
  formatter: function (x) { return x + "%"}
});

Would it be possible to show the Label AAA data when the page opens regardless of its value being lower or higher than Label BBB?

setting sortData: false doesn't seem to work.

Thanks.

**Comment by jakesylvestre** [comment]
Updating dead link: Issue is #149
