### ISSUE TITLE
How to update the graph with incoming data?

### ISSUE THREAD

**Issue by bondarewicz** [morrisjs/morris.js#207]
Let's presume graph is initialised with just one JSON item for graph data on page load. 
Using web sockets I'm trying to push into it every time there is new event. 

How can I re-draw/update graph?

**Comment by londonuk371** [comment]
There might be a bug on dates display. The solution I found to redraw the chart with new datas comes with emptying the element containing the chart with .html(""):

`function _redrawChart() {

  $("#DivChartAccounts").html("");
  graphAccounts = Morris.Line({
    element: "DivChartAccounts",
        data: [
            { y: "2016-09-18", a: 429 },
            { y: "2016-09-19", a: 534 },
            { y: "2016-09-20", a: 614 },
            { y: "2016-09-21", a: 614 },
            { y: "2016-09-22", a: 198 },
            { y: "2016-09-23", a: 400 },
            { y: "2016-09-24", a: 454 },
            { y: "2016-09-25", a: 715 },
            { y: "2016-09-26", a: 555 },
            { y: "2016-09-27", a: 508 },
            { y: "2016-09-28", a: 344 },
            { y: "2016-09-29", a: 244 },
            { y: "2016-09-30", a: 286 },
            { y: "2016-10-01", a: 595 },
            { y: "2016-10-02", a: 185 },
            { y: "2016-10-03", a: 95 }
        ],
    xkey: "y",
    ykeys: ["a"],
    labels: ["Total"],
    lineColors: ["#9c9c9c"],
    lineWidth: "3px",
    resize: true,
    redraw: true,
    parseTime: false
  });

}`

**Comment by xaifuddin** [comment]
How to get data from PHP variable ?
ex: `{ y: "2016-09-18", a: <?php echo $dataVar ?> }`

**Comment by djzdavid** [comment]
like this ->

```
$data = '[[{"d": "2012-10-01", "visits": 802}, {"d": "2012-10-02", "visits": 783}, { "d": "2012-10-03", "visits": 820}]]';

$final = json_decode($data, true);
$new_final = array();
// simple flattening
foreach ($final as $value) {
    foreach ($value as $sub_value) {
        $new_final[] = $sub_value;
    }
}

echo json_encode($new_final);
```
