### ISSUE TITLE
Donut chart - have no segments selected by default?

### ISSUE THREAD

**Issue by CodilX** [morrisjs/morris.js#216]
Is it possible to have no segments selected by default, and also to remove the inner text once the mouse has cleared the particular segment? So that the information would be visible only when hovered on a particular piece, instead of having one of the segment always selected?

Edit: I've managed to disable the auto select by commenting out line 1430 in morris.js, but is there a way to deselect the segment after mouse out?

Edit2: Also, is there a callback when entering, leaving a segment? I'd like to create a inner circle div that get's faded in when a user hovers on a segment, and have it faded out when the users leaves it.

**Comment by kholmukhamedovme** [comment]
> Is it possible to have no segments selected by default

I work with compiled js, you can just delete [this if condition block](https://github.com/morrisjs/morris.js/blob/master/morris.js#L1931) and segments won't be selected by start.
