### ISSUE TITLE
Export the graph to downloadable image by the user.

### ISSUE THREAD

**Issue by dariojr** [morrisjs/morris.js#249]
Hello, first of all want to thank all the work done to make this library work as well.
I'm working with Morris, and now I need to export the graph produced an image file as a png.
Is there any possible solution?
Tanks

**Comment by aamin3189** [comment]
This could help
https://jsfiddle.net/aamin89/c3uLkLuh/1/
New link (working)
https://jsfiddle.net/aamin89/ucsozbzd/4/

**Comment by Purush0th** [comment]
@aamin3189  This is so helpful but IE (11) is not supporting.

**Comment by FranMM7** [comment]
is there a new method to export any Chart to pdf o image at least?

**Comment by Fahmiibrahim** [comment]
not working on IE
