### ISSUE TITLE
Drawing vertical grid lines

### ISSUE THREAD

**Issue by alexvb** [morrisjs/morris.js#254]
It would be nice if Morris could draw vertical grid lines for labels on the x-axis, too. Is this a reasonable feature?

**Comment by Faisal-nfl** [comment]
can any one tell me that how to use this
I tried verticalGrid: true
But noting happened

**Comment by pierresh** [comment]
This option works well in [my fork](https://pierresh.github.io/morris.js/), the type of vertical grid can even be set through the option **verticalGridType**.
