### ISSUE TITLE
dynamic data with jquery ajax dont work

### ISSUE THREAD

**Issue by karev** [morrisjs/morris.js#30]
hello community, i try to append data dynamically to morris using jquery $.get() $.load() ,with and without json encode but that dont work itried also a hidden iput alwaus give same probleme the browser block :( but using php it work perfectly there is any way how to do it ??

**Comment by Rayner061** [comment]
Can you please share your code please. i'm having the same problem

**Comment by Rayner061** [comment]
$("#diseaseselection").change(function(){
            $("#chart").empty();
            var diseaseselection = $("#diseaseselection").val();
            $.ajax({
                url: "chart.php",
                method: "POST",                   
                data: {
                    diseaseselection: diseaseselection
                },
                success: function(data) {
                    var graphdata = data;
                    console.log(graphdata)
                    Morris.Line({
                        element : 'chart',
                        data:[graphdata],
                        xkey:'totalF',
                        ykeys:[ 'totalM'],
                        labels:['Total MALE'],
                        hideHover:'auto',
                        pointStrokeColors: ['white'],
                        lineWidth:'6px',
                        parseTime: false,
                        lineColors: ['Skyblue', 'Pink'],
                    });
                }
            });
        });

**Comment by Rayner061** [comment]
```
include_once('connection.php');
$diseaseselection = $_REQUEST['diseaseselection'];
if(isset($diseaseselection)){
	$result = mysqli_query($con, "SELECT disease,age,SUM(CASE WHEN gender = 'm' THEN 1 ELSE 0 END) AS `totalM`, SUM(CASE WHEN gender = 'f' THEN 1 ELSE 0 END) AS `totalF` FROM mdr where disease = '$diseaseselection' GROUP BY disease , age");
	$chart_data = '';
	while($row = mysqli_fetch_array($result))
	{
		$tabx[]=$row['totalF'];
		$taby[]=$row['totalM'];

	}
	$tableau=array_combine($tabx,$taby);
	foreach($tableau as $key=>$value){
	$string[]=array('totalF'=>$key,'totalM'=>$value);

	}
	echo json_encode($string);
}
```
