### ISSUE TITLE
Long xLabels truncated when using xLabelAngle

### ISSUE THREAD

**Issue by shnads** [morrisjs/morris.js#316]
Any x label longer than 12 characters is truncated by the bottom of the SVG when using xLabelAngle of 60 on a barchart (possibly other combinations too). If I use firebug to increase the SVG height after the bar chart has loaded the issue is resolved. Makes this otherwise awesome library unusable with long labels.

**Comment by cirovargas** [comment]
This dont fix Morris Bar vertical xLabel?

![screenshot from 2016-11-15 00-57-35](https://cloud.githubusercontent.com/assets/1972562/20291644/bea85bb8-aace-11e6-9e4f-90d01a7c76af.png)

**Comment by lakitaki** [comment]
@cirovargas Is this fixed or not? I also could not find the answer.

**Comment by page1990** [comment]
It works for me
