### ISSUE TITLE
How to make legends?

### ISSUE THREAD

**Issue by shgninc** [morrisjs/morris.js#346]
Hi there. Thanks for this project.
How can i make a legend for may Bar chart?

**Comment by gamov** [comment]
Thank you @sudodoki for your snippet. Very useful if the graphs are made to be printed.

**Comment by shahriarhossain** [comment]
@sudodoki : I am in need of legend in Donut Charts. 
![donuts with legend](https://cloud.githubusercontent.com/assets/6463320/16034598/7d912810-31c7-11e6-8b57-90a40a395fa1.png)
any code snippet will help

**Comment by dima-sh** [comment]
@shahriarhossain check this [https://jsfiddle.net/x1q12so2/](https://jsfiddle.net/x1q12so2/)

**Comment by kavin-90** [comment]
@shahriarhossain I want same as you too. Anyone got solution?

**Comment by Kasara** [comment]
Because dima-sh has posted nearly the whole thing (thanks!),
I completed (and simplified) it:

https://jsfiddle.net/h0fjm80n/

No more css. Also it shows the value right of the text.

**Comment by coolananth** [comment]
how about for Bar chart??

**Comment by dsilva0101** [comment]
Hello,

How can I change the size font of legend in line chats?

**Comment by ocramot** [comment]
@coolananth  you can do it with bar charts this way:
https://jsfiddle.net/9zwzzqu7/2/

**Comment by ravistm** [comment]
For Bar Chart full code: (this will put the legend at the top right corner of the bar chart div)

**HTML**
```
<div class="grid-body no-border">
 <div id="visitor_legend" class="bar-chart-legend"></div>
 <div id="visitors_bar_chart" style="height:250px"></div>
</div>
```
**JS CODE**
```
var browsersChart = Morris.Bar(config);

    // Legend for Bar chart
    browsersChart.options.labels.forEach(function(label, i) {
        var legendItem = $('<span class="legend-item"></span>').text( label).prepend('<span class="legend-color">&nbsp;</span>');
        legendItem.find('span')
          .css('backgroundColor', browsersChart.options.barColors[i]);
        $('#visitor_legend').append(legendItem)
   });
```

**CSS:**

> .bar-chart-legend {
>   display: inline-block;
>   right: 25px;
>   position: absolute;
>   top: 8px;
>   font-size: 10px;
> }
> 
> .bar-chart-legend .legend-item {
>   display: block;
> }
> 
> .bar-chart-legend .legend-color {
>   width: 12px;
>   height: 12px;
>   margin: 3px 5px;
>   display: inline-block;
> }
![barchart-legend](https://user-images.githubusercontent.com/5778777/51983590-13242480-24bf-11e9-93b7-d1a1b8b739e9.png)

**Comment by ravistm** [comment]
asfd
