### ISSUE TITLE
null data (no data) for the graph

### ISSUE THREAD

**Issue by sirNemanjapro** [morrisjs/morris.js#394]
For example, you are presenting an area graph that spans through 12 months, but you only have data for 5 months.

1) If you set the value to 0 you get a flat chart. That is not visually pleasing since there is no data and the value is never zero.

2) If you omit the value from the chart your area chart wont load.

Is there a chance to omit the value, set it as null or anything else in order for the chart not to break and draw the graph line just for those 5 consecutive months (out of 12)?

**Comment by heegar** [comment]
Is there a way to handle the situation where there is a null in the middle of 2 valid data points and have the line be continuous instead of broken?

**Comment by bilaalshah** [comment]
Hey @heegar @ebeigarts 

can i hide the color if the values are from zero ?

![screenshot 157](https://user-images.githubusercontent.com/5277834/36676813-73d690a6-1b2e-11e8-87b3-594ff8fe15db.png)

I mean to hide the shaded area of that zero values.. basically the 2 values are null and 1 50,000 so i want to hide the shade of null values .. can i do that ?

**Comment by pierresh** [comment]
Yes, the Area charts consider null points as 0... I will try to correct in couple of days. A workaround would be to give these points the same value as the yellow curve.
