### ISSUE TITLE
Get bars and lines on a same chart

### ISSUE THREAD

**Issue by cphilippe-ch** [morrisjs/morris.js#415]
Hi Olly,
Thanks for your amazing work !
I would like to know if it's possible to merge on a single chart some bar and some lines if the x scale is the same.

Many thanks

![example](https://cloud.githubusercontent.com/assets/5197911/3066737/d6377374-e279-11e3-8990-a72233ef6aa5.jpg)

**Comment by abhishek-g** [comment]
Can anyone tell me how to this??? is it possible ??

**Comment by JelteF** [comment]
Only if you want straight lines. In that case you can use goals. But
otherwise no.

**Comment by vrdriver** [comment]
+1 for this. Any updates?
