### ISSUE TITLE
Month names in label (xkey)

### ISSUE THREAD

**Issue by sirNemanjapro** [morrisjs/morris.js#416]
Am I doing something wrong, because I cant get xLabels to show month names (April, May, June...)?

I used 

```
        data: [
            { month: '2014-01', value: 350 },
            { month: '2014-02', value: 440 },
            { month: '2014-03', value: 440 },
            { month: '2014-04', value: 405 },
            { month: '2014-05', value: 390 },
            { month: '2014-06', value: null },
            { month: '2014-07', value: null },
            { month: '2014-08', value: null },
            { month: '2014-09', value: null },
            { month: '2014-10', value: null },
            { month: '2014-11', value: null },
            { month: '2014-12', value: null }
        ],
        xkey: 'month',
```

but it only showed the year - 2014 in the x line, not even months as written (i.e. 2014-05).

**Comment by eloisemonteiro** [comment]
Hello, I'm trying to print all the months on the x line to compare but it's only printing the January, could you help me ?


var months = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'];
    Morris.Line({
        element: 'morris-line-chart',
       data: [
            { month: '00',  a: 100, b: 90},
            { month: '01',  a: 100, b: 90 },
            { month: '02',  a: 100, b: 90},
            { month: '03',  a: 100, b: 90},
            { month: '04',  a: 100, b: 90 },
            { month: '05',  a: 100, b: 90 }
        ],
        xkey: 'month',
        ykeys: ['a', 'b'],
        labels: ['2015', '2014'],
        hideHover: 'auto',
        resize: true,       
      xLabelFormat : function (x) {
      return months[x.getMonth()];
      }
    });




});

**Comment by basmoura** [comment]
@eloisemonteiro it's because need also define the year
