### ISSUE TITLE
Multiple values for same key (day)

### ISSUE THREAD

**Issue by fabricespee** [morrisjs/morris.js#421]
Is there a possibility to have multiple values for the same key (day), if parseTime true?

Example
data: [
{ day: '2014-06-01', y: '20' },
{ day: '2014-06-01', y: '21' },
{ day: '2014-06-02', y: '15' }
 ]

When I do this, the value bullets/points are overlaying each other.

**Comment by CristianaPereira** [comment]
I'm a little late (2 years), but hopefully it will help someone else.
Ther's an option to do that, its 'parseTime', just set it to false. You can search it here http://morrisjs.github.io/morris.js/lines.html.
