### ISSUE TITLE
Morris Line Chart - X axis Label is missing

### ISSUE THREAD

**Issue by differenz-manan** [morrisjs/morris.js#425]
I am using morris chart in my application.
In this chart , everything seems to be fine but the label for last date is not visible on x -axis.
See Image

This is my code for line chart:

Morris.Line({
                                element: 'dvRegisteredUserbyDate',
                                data: [{ "User_Creation_Date": "2014-05-24", "RegisteredCount": 587 }, { "User_Creation_Date": "2014-05-25", "RegisteredCount": 65 }, { "User_Creation_Date": "2014-05-27", "RegisteredCount": 1 }],
                                xkey: 'User_Creation_Date',
                                ykeys: ['RegisteredCount'],
                                labels: ['Registered'],
                                pointSize: 4,
                                lineColors: ["#7e9d3a"],
                                xLabels: 'day'
                            });

Thank you.
![morris-chart](https://cloud.githubusercontent.com/assets/7823606/3208525/cfd461f6-ee39-11e3-9821-334d9de7a1da.png)

**Comment by kamal-el** [comment]
hi, 
how to add a title of chart  and axes
