### ISSUE TITLE
[help|idea] how to create chart (bar + line chart )

### ISSUE THREAD

**Issue by arisrpl** [morrisjs/morris.js#505]
Hi, thx mate for great plugin :D

I want to know, is it possible to create chart bar with  include line ?

I can create  chart bar
![ori](https://cloud.githubusercontent.com/assets/5050913/4514813/85bcaf10-4b90-11e4-87f2-7be8d8a4fd81.jpg)

my goal is, to add the line (with diffrent value )
![kepinginya](https://cloud.githubusercontent.com/assets/5050913/4514816/b0e0bfe2-4b90-11e4-9061-42923abe2c2b.jpg)

thx before,
and sorry for my bad english.

**Comment by Newtonishappy** [comment]
Up this ! Cause it could be very useful indeed ! 

I'm doing a Line chart but i'll really appreciate to add a bar chart to it ! 

Thx pour the plugin !

**Comment by Haikane** [comment]
+1

**Comment by arisrpl** [comment]
I already finish this. 
but sorry all of my source source code already stored on my ex-company (i'm not working again).

but you need 3 variable , (time , on (probaly the blue bar) ,someValue(red) ),
you can combine it , but i forgot how I do that (with this plugin)
