### ISSUE TITLE
How do I add a new Series to a graph dynamically?

### ISSUE THREAD

**Issue by kanish671** [morrisjs/morris.js#523]
I would like to add Data containing the same x-labels but different y-labels to the existing data and show it using a different colour (i.e. a new Series). setData() does not help me in this as it replaces the data. Pushing into existing data and calling setData() requires me to hard code the series names and initialize them during declaration.
Here is an example.
http://jsbin.com/nifinoyibe/1/edit?js,output
Here, I had to pre-define the series 'c'. What I want is some mechanism where I do not have to pre-define 'c', but can add it later. Is there a feature that helps me do this? Or would I have to hard code this new series? (PS: I may have to add more than 3 new series dynamically)

**Comment by rivaldid** [comment]
Could you share a working example? I'm having troubles with this method

**Comment by kanish671** [comment]
@rivaldid http://jsbin.com/jihojajada/edit?js,output
Check the jsbin out. I modified it with the inputs from JelteF
