### ISSUE TITLE
Update goal values dynamically

### ISSUE THREAD

**Issue by pierresh** [morrisjs/morris.js#527]
Hello,

I am using morris.js on one page dynamically refreshed with ajax. It is indeed possible to update the chart thanks to the function setData(). Nevertheless, I have not found any way to update goal values dynamically (i.e. with a function called setGoals()). Is it possible ?

By the way, congratulations to every contributor, this plugin is awesome!

Alplob

**Comment by 0000day** [comment]
But that has a horrible performance as the data gets fully set again. I've tried calling `chart.redraw()` but this unfortunately hasn't any effect. I want to set the goals/events with a slider-value. If I pick up the slide-event (many calls) it shows off the bad performance. I mean, it would just have to redraw the goals/events itself, not recalculate the data...

No way for this?
