### ISSUE TITLE
How to round yLabels

### ISSUE THREAD

**Issue by ozgrozer** [morrisjs/morris.js#553]
I have an area chart like this.
![](http://i.imgur.com/QWZSw8N.jpg)

How can I round the yLabels like [0,2,4,6,8]?

**Comment by DeluxZ** [comment]
I had the same problem. Fixed it with the yLabelFormat options like this

``
 yLabelFormat: function(y) { return y != Math.round(y) ? '' : y; },
``

**Comment by ozgrozer** [comment]
It works :) Thanks.
