### ISSUE TITLE
Legend below bar chart

### ISSUE THREAD

**Issue by andregsilv** [morrisjs/morris.js#557]
Hi, 
I have a bar chart with two series. And there are only two bars in the chart: the first one from the A series, and the second one from the B series.

How could I draw two labels below the two bars? (with **resize** enabled)
Is this features already in the library?

**Comment by andregsilv** [comment]
Is there some resizeCallback?

**Comment by JelteF** [comment]
Could you give an example in a jsbin/jsfiddle to show what you mean?

**Comment by JelteF** [comment]
And as for the resizeCallback I don't believe there is one.

**Comment by andregsilv** [comment]
![capturar](https://cloud.githubusercontent.com/assets/1469412/6005762/02e8d2f8-aaf4-11e4-8098-d3fe55520761.PNG)

I want to do something like this, but I don't know how to add individual legends for each bar.

**Comment by JelteF** [comment]
Hmmm, that's not really built in functionality since that is not how you normally use the chart. That info is now in the hover. What you could do is try to supply a hoverCallback that does that.

**Comment by andregsilv** [comment]
Thank you.
I'll replace it for a donut.
