### ISSUE TITLE
setData and ymax / ymin

### ISSUE THREAD

**Issue by jwkellyiii** [morrisjs/morris.js#565]
Why can't I update the ymax / ymin when using setData? If the data I am updating has a much larger range, the are goes off the chart. I would use ymin / ymax: auto [num], but I don't want my chart y-axis to start at 0 since my data goes up to 5+ million [0 to 5 million y-axis makes the chart useless].

**Comment by JelteF** [comment]
If you change the options object in the graph instance before calling setData on it it will use the new options object. So you could change the ymax/ymin there.

**Comment by jwkellyiii** [comment]
There is the key: 

You MUST use graph.options["ymin"] and graph.options["ymax"]

NOT

graph.ymin and graph.ymax

Thanks.

**Comment by JelteF** [comment]
graph.options.ymin would also work btw.
