### ISSUE TITLE
Exerpt xLabels on x axis but not in the tooltip hover.

### ISSUE THREAD

**Issue by ExcellentSP** [morrisjs/morris.js#575]
I'm using a the xLabelFormat option to shorten the labels on the x axis to 15 characters, but I want to be able to show the whole label text inside of the hover tooltip.

`xLabelFormat: function (x) { return x.label.substring(0, 15) + '...'; },`

I don't quite know how to do this, and I've looked through the documentation, but to no avail. Is there a simple way to do this, or does the functionality need to be added?

**Comment by JelteF** [comment]
You could use the hoverCallback function to change the default contents of the hover tooltip.
