### ISSUE TITLE
Get Data from DOM-List elements to make chart

### ISSUE THREAD

**Issue by blag001** [morrisjs/morris.js#578]
Hello.
Can you add a feature that allow us to use a ul/li list to supply data ?
Like many people, I put my JQuery import at the end of my html file.
So if I want to make chart, I should put my data in a JS var at the end of the file : not really cool...
And not user friendly if I want to let my mother use it (hard to make a BBcode)...

Why we can't, in the `<div id="chartTarget">`, put a ul/li list with our data ? 
like https://github.com/zurb/pizza does : 

``` html
<div id="myfirstchart" style="height: 250px;">
    <ul>
        <li data-value="15">Foo</li>
        <li data-value="25">Bar</li>
        <li data-value="60">Foobar</li>
    </ul>
</div>
```

If you don't have a `data:[array]` in the `new Morris.Line()` call, you check for a DOM content to parse.

**Comment by JelteF** [comment]
You can use the li items yourself to get the data into javascript and supply it to the constructor of the graph.

**Comment by blag001** [comment]
For now the best I've got is this : 
```html
<div class="donut" style="height: 150px;" data-donut='[
    {"label": "Foo", "value": 70},
    {"label": "Bar", "value": 25},
    {"label": "Foobar", "value": 5}
  ]'></div>
<!-- ... -->
<script type="text/javascript">
//Morris charts snippet - js
$.getScript("http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js",function(){
	$.getScript("http://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.0/morris.min.js",function(){
		$(".donut").each(function(){
			Morris.Donut({
				element: $(this),
				data: $(this).data("donut")
			});
		});
	});
});
</script>'
```
I know we can make the Li support by ourself (even if for now mine won't work u_u"), but why it's not a native data supplying method ?
I mean, it's hard ? 
Really not useful ? (maybe I'm the only one who need this, but for my, the JS chart is just a graphical overlay for a data table) 

Thank for the quick reply.
Blag

**Comment by JelteF** [comment]
The main reason is that there is a million ways to lay out data on a page and it differs per person how that is done. The lib supplies an easy JS interface to give it the data and it would get bloated if every way of supplying data would be integrated into it.

**Comment by blag001** [comment]
Ok "keep it simple".
Even if for me, one DOM way (li; data-* or anything) is a good complement of the JS one.

I put this "[Morris donut chart, asynchronous from DOM](https://jsfiddle.net/nwdq1xjz/)"  here, if someone need it...

I close; thank you +
