### ISSUE TITLE
Morris Area Chart

### ISSUE THREAD

**Issue by Caneco** [morrisjs/morris.js#588]
How could this be right?
**Hasn't supposed to the "pink" area chart be bigger than the other two?**

![screen shot 2015-05-30 at 15 09 54](https://cloud.githubusercontent.com/assets/502041/7897712/117531c2-06de-11e5-89db-4b0cd3de337c.png)

**Comment by JelteF** [comment]
That Is only if you use line charts, this is an area chart. In which the amounts are stacked so the total can be seen easily.
