### ISSUE TITLE
Hovers not being displayed

### ISSUE THREAD

**Issue by snehaheda** [morrisjs/morris.js#593]
I added a bar chart using the library but i have one main issue that the hover is not being rendered and i have no idea.
Below is my code
        Morris.Bar({
              element: 'bar-example',
              data: jQuery.parseJSON(grpdata),
              xkey: 'name',
              ykeys: ['data'],
              labels: ['Hrs'],
              xLabelAngle: 60,             
              barColors:function (row, series, type) {                  
                  return $('#'+row.label).css('background-color');
              },
              hideHover: 'auto',
       });

As soon as i remove the barcolors option from the above code the hover works. But i need bars have different colors based on the settings stored

**Comment by leriel** [comment]
There is a good chance that `$('#' + row.label)` elements do not exist at the time barColors is called.

Try initiating Morris when DOM is ready - in below example i simply wrapped Morris call in $(document).ready

http://jsbin.com/mogumulupo/1/edit?html,css,js,output

Either way, by all means - look into what barColors is actually returning - for example 

```js
barColors: function (row, series, type) {
  var ret = $('#'+row.label).css('background-color');
  console.log('barColors returned', ret);
  return ret;
},
```

**Comment by snehaheda** [comment]
Thanks for the pointer. I was already calling it in dom ready. But the issue was space in Id.
