### ISSUE TITLE
Text based x axis labels

### ISSUE THREAD

**Issue by devswap** [morrisjs/morris.js#594]
I believe the default x axis label is number / date related but I see some charts with x axis items such as iphone 3s, iphone 4 etc which clearly are not numeric. Please could you tell me how I go about adding these.

Thanks

**Comment by devswap** [comment]
Its ok i discovered what do to. Just in case any one is wondering its just change the data label, reference that label in the xkey, and then add parseTime: false,

**Comment by abhis88** [comment]
Thanks a lot.
