### ISSUE TITLE
Make CommonJS friendly

### ISSUE THREAD

**Issue by jphamilton** [morrisjs/morris.js#595]
Two changes are needed to make this project more friendly to Node. First, the NPM package should be renamed to "morris". I can't speak for all environments, but I cannot resolve "morris.js" using Webpack. Anyway, the NPM standard is to remove .js from the package name as it's assumed everything is js in the first place.

Also, please add 
"main": "morris.min"

to the package.json file. This allows me to use require.

**Comment by DHFW** [comment]
+1 I'm having the same issue, cannot use it with webpack...

**Comment by booleanhunter** [comment]
+1 Same here!

**Comment by ArtemMaximum** [comment]
+1

**Comment by nneal** [comment]
This was still not working for us, it appears the team did not push `0.5.1` to npm. We made our own 

https://github.com/GovPredict/govpredict-morris
https://www.npmjs.com/package/govpredict-morris

Usage:
```
import morris from 'govpredict-morris';
```
