### ISSUE TITLE
Pie Chart no option

### ISSUE THREAD

**Issue by cabepao** [morrisjs/morris.js#604]
I'm researching over the whole internet to look if pie chart can show values on each segment but i cant find any answer. I wonder if the morris.js library can help to do that because i dont want to use another library. Its an excellent library but i need one option to show values by default with no need to hover each segment to show the values.
Maybe in the centre would be a general value and on each segment a tooltip showing the value of each segment (im sorry for redunding).

**Comment by jaminellis** [comment]
See the live example: http://morrisjs.github.io/morris.js/ You can have values display on hover.

**Comment by cabepao** [comment]
Jaminellis, i was talking specially for pie chart, is not possible to have on each segment its value instead of hover to have visibility of the values?

**Comment by cabepao** [comment]
Jaminellis, i was talking specially for pie chart, is not possible to have
on each segment its value instead of hover to have visibility of the values?
