### ISSUE TITLE
Onclick event

### ISSUE THREAD

**Issue by mns69** [morrisjs/morris.js#623]
Hi,

I have two y-axis series, for example
Morris.Bar({
  element: 'bar-example',
  data: [
    { y: '2006', a: 100, b: 90 },
    { y: '2007', a: 75,  b: 65 },
    { y: '2008', a: 50,  b: 40 },
    { y: '2009', a: 75,  b: 65 },
    { y: '2010', a: 50,  b: 40 },
    { y: '2011', a: 75,  b: 65 },
    { y: '2012', a: 100, b: 90 }
  ],
  xkey: 'y',
  ykeys: ['a', 'b'],
  labels: ['Series A', 'Series B']
});
I have a situation where on-click I have to get which y-axis series i have clicked. I tried onclick code
.on('click', function(i, row){
  //my code
})
But from this I am not able to get which y-axis i clicked.
Can you help me out with this

**Comment by niraj-shah** [comment]
The ```row``` variable will contain the data from the point that was clicked.

You can then do ```row.a``` or ```row.b``` to see the values.

**Comment by mns69** [comment]
Thank you for your reply.
But I want to know which y-axis I clicked not the value of axis.

**Comment by satyendrakumarsingh** [comment]
Its simple to get the y-axis on click.
Below code simply alert X and Y-Axis both. 

```
Morris.Bar({
    element: 'third',
    data: [
    { y: '2006', a: 100, b: 90 },
    { y: '2007', a: 75, b: 65 },
    { y: '2008', a: 50, b: 40 },
    { y: '2009', a: 75, b: 65 },
    { y: '2010', a: 50, b: 40 },
    { y: '2011', a: 75, b: 65 },
    { y: '2012', a: 100, b: 90 }
    ],
    xkey: 'y',
    ykeys: ['a', 'b'],
    labels: ['Series A', 'Series B']
    }).on('click', function(i, row) {        
           alert("X-Axis: "+ row.a +" and " +row.b);
           alert("Y-Axix: "+row.y);           
 });
```

The above example is based on your post in case of if you change your xKey and yKeys value you need to change row.y, row.a and row.b as per your changes.

**Comment by mns69** [comment]
Thanks for the reply.
But as I mention above I want to know which y-axis (Series A or Series B) I clicked not the value of axis.

**Comment by satyendrakumarsingh** [comment]
That is not possible directly or by using any API method. 
But I have one solutions for that series and value both. For explanation what and how it works refer the link issue on area graph I have replied. 

#689 

**Note - It works well but make sure you have set different colors for the every yKeys.** 

```
Morris.Bar({
    element: 'third',
    data: [
        { y: '2006', a: 100, b: 90 },
        { y: '2007', a: 75, b: 65 },
        { y: '2008', a: 50, b: 40 },
        { y: '2009', a: 75, b: 65 },
        { y: '2010', a: 50, b: 40 },
        { y: '2011', a: 75, b: 65 },
        { y: '2012', a: 100, b: 90 }
    ],
    xkey: 'y',  
    ykeys: ['a', 'b'],
    labels: ['Series-A', 'Series-B']
    }).on('click', function(i, row) {       
         //  console.log(row); 
    });

    function getSeries(event) {
       var rectCol = this.getAttribute("fill");    
       $(".morris-hover-point").each(function() {
            var labStyle = this.getAttribute("style");
            var labCol = labStyle.slice(labStyle.indexOf(":")+1);           

            if(rectCol.trim() === labCol.trim()) {
                console.log("You have clicked on: "+this.textContent);          
            }
        });    
    }

    $(document).on('click', 'rect', getSeries);
```

![bar-graph](https://cloud.githubusercontent.com/assets/16490760/19473149/f2c86e20-9547-11e6-849e-f85c714cb9ba.png)

**Comment by mns69** [comment]
It worked perfectly. Thanks a lot.
