### ISSUE TITLE
Memory leak when redrawing graphs

### ISSUE THREAD

**Issue by senexada** [morrisjs/morris.js#64]
When I call Morris.Line(...) many times within a web page, the browser leaks memory.

I noticed the problem when designing a web page that uses a 1 second timeout to load new data points (via ajax), then I plot the new points using Morris.Line().  Thus the webpage has the appearance of a rolling graph, which looks great.  But the browser leaks memory like crazy (1MB/second or more in my project).

Ajax might contribute to the leaks, so I created a simple example with no ajax (html below).   My browser leaks around 5MB/minute while viewing the sample.   I measure the leaks using Windows Task Manager.  I'm running Windows 7 Professional.  I see similar leakage rates in Chrome 17.0.963.79 m and Firefox 12.0 .  

<html>
<head>
<title>Real time data</title>

<script src="js/jquery-1.7.1.min.js"></script>

<script src="js/raphael-2.0.2-min.js"></script>

<script src="js/morris.min.js"></script>

</head>
<body>
Graph 0

<div class='graph' id='graph0'></div>

<div id='reloadStatus'></div>

<script>
var nReloads = 0;
function draw() {

  Morris.Line({
    element: 'graph0',
    data: [
      {'date': '2012-06-01 15:06:57', 'Apples': 672, 'Bananas': 644, 'Oranges': 185, 'Peaches': 218, 'Pears': 0},
      {'date': '2012-06-01 15:06:58', 'Apples': 380, 'Bananas': 259, 'Oranges': 65, 'Peaches': 115, 'Pears': 0},
      {'date': '2012-06-01 15:06:59', 'Apples': 305, 'Bananas': 258, 'Oranges': 60, 'Peaches': 132, 'Pears': 0},
      {'date': '2012-06-01 15:07:00', 'Apples': 568, 'Bananas': 481, 'Oranges': 137, 'Peaches': 215, 'Pears': 0},
      {'date': '2012-06-01 15:07:01', 'Apples': 654, 'Bananas': 538, 'Oranges': 162, 'Peaches': 265, 'Pears': 0},
    ],
    xkey: 'date',
    ykeys: ['Apples', 'Bananas', 'Oranges', 'Peaches', 'Pears'],
    labels: ['Apples', 'Bananas', 'Oranges', 'Peaches', 'Pears'],
    parseTime: false,
    hideHover: true,
    ymin: 0,
    ymax: 'auto 100'
  });

  nReloads++;
  $('#reloadStatus').text(nReloads + ' reloads');
  setTimeout(function() { draw(); }, 1000);
}
draw();
</script>

</body>
</html>

**Comment by xaifuddin** [comment]
How to get data from SQL ?
