### ISSUE TITLE
% sign can not be add

### ISSUE THREAD

**Issue by harshadduasane** [morrisjs/morris.js#665]
I want to add **"%"** sign after value in **morris.donut chart**
Please help me to solve.
Thanks in advance

**Comment by LukaszDev** [comment]
Use:
`formatter: function (x) { return x + ' %' }`

It's on first page of [Donut Charts docs](http://morrisjs.github.io/morris.js/donuts.html) ;)

**Comment by harshadduasane** [comment]
Thanks LukazDev.
