### ISSUE TITLE
how to change xkey in morris line chart to string?

### ISSUE THREAD

**Issue by idris11** [morrisjs/morris.js#681]
<script>
  $(function () {
    // LINE CHART
    Morris.Line({
      element: 'myfirstchart',
      resize: true,
      data: [
        {x: '1', IP: <?php echo json_encode($hasil_item['1']); ?>},
        {x: '2', IP: <?php echo json_encode($hasil_item['2']); ?>},
        {x: '3', IP: <?php echo json_encode($hasil_item['3']); ?>},
        {x: '4', IP: <?php echo json_encode($hasil_item['4']); ?>},
        {x: '5', IP: <?php echo json_encode($hasil_item['5']); ?>},
        {x: '6', IP: <?php echo json_encode($hasil_item['6']); ?>},
        {x: '7', IP: <?php echo json_encode($hasil_item['7']); ?>},
        {x: '8', IP: <?php echo json_encode($hasil_item['8']); ?>}
        ],
      xkey:'x',
      ykeys: ['IP'],
      labels: ['IP'],
      lineColors: ['#3c8dbc'],
      hideHover: 'auto'
    });

  });
</script>

**Comment by satyendrakumarsingh** [comment]
You can display xKey as string in line chart refer the below simple example.

```
Morris.Line({
          element:'yourChartId',
          data: [           
                    {week:'MON', "sale":'20',  "cash":'25',  "cheque":'41', "void": '8', "declined": '13'},             
                    {week:'TUE', "sale":'56',  "cash":'12',  "cheque":'25', "void": '18', "declined": '8'},             
                    {week:'WED', "sale":'156',  "cash":'36',  "cheque":'11', "void": '5', "declined": '6'},             
                    {week:'THU', "sale":'125',  "cash":'58',  "cheque":'22', "void": '13', "declined": '22'},               
                    {week:'FRI', "sale":'158',  "cash":'28',  "cheque":'6', "void": '7', "declined": '14'},             
                    {week:'SAT', "sale":'166',  "cash":'7',  "cheque":'13', "void": '9', "declined": '3'},              
                    {week:'SUN', "sale":'169',  "cash":'33',  "cheque":'19', "void": '22', "declined": '18'}
           ],
           xkey: 'week', 
           ykeys: ['sale','cash', 'cheque', 'void', 'declined'],
           labels: ['Sale', 'Cash', 'Cheque', 'Void', 'Declined'],
           parseTime:false,
           hideHover:true,
           lineWidth:'6px',
           stacked: true           
        }).on('click', function(i, row){
          console.log(row);
    });
```

![transaction-report](https://cloud.githubusercontent.com/assets/16490760/19438687/d168349a-9498-11e6-87d7-27203202eed2.png)

**Comment by bhargavmullakuru** [comment]
Working fine...Thank you @satyendrakumarsingh

**Comment by dexit** [comment]
This has saved me tons of time :)

**Comment by satyendrakumarsingh** [comment]
I am glad that i am able to help you @dexit

**Comment by sparkle32817** [comment]
Thanks, Very clear example!
