### ISSUE TITLE
Donut bar on hover

### ISSUE THREAD

**Issue by alejodiazg** [morrisjs/morris.js#687]
Hello.

Im using your library to show some data for my clients, most of it using the donut graph.

Currently im looking to set up a mouse enter and a mouse leave event to make my ui highlight the corresponding information in the details table.

i know I can do this to set up a click on each part of the donut

```
morris = new Morris.Donut({
                element: elem,
                data: scope.donutData,
                colors: colors || ['#0B62A4', '#3980B5', '#679DC6', '#95BBD7', '#B0CCE1', '#095791', '#095085', '#083E67', '#052C48', '#042135'],
                resize: true
              }).on('click' , function(i , row){
                console.log(row.label);
                console.log(i, row);
              });
```

but when i try with 'mouseenter' , 'mouseleave' it does nothing, this is a feature thats implemented or will I need to hack something in the cofeescript code? If its implemented I could use some help on how its used.

Thanks.

**Comment by alejodiazg** [comment]
Hi, not getting answers yet but ill put here my solution (as I still dont know coffescript) I modified the javascript in a simple way, I noticed a select function in the donut behaviour, and that in the click one it fired a 'click' event, now I replicated that on the select firing an select event, now I set up the graph like this

`
morris = new Morris.Donut({
                element: elem,
                data: scope.donutData,
                colors: colors || ['#0B62A4', '#3980B5', '#679DC6', '#95BBD7', '#B0CCE1', '#095791', '#095085', '#083E67', '#052C48', '#042135'],
                resize: true
              }).on('selected' , function(i , row){
                console.log(row.label);
                console.log(i, row);
              });
`

Ill learn coffescript soon so I can publish a fork with this function.

If u want to know why this could be usefull, u can do things like this.
![image](https://cloud.githubusercontent.com/assets/5624658/19329019/a8bb76a8-90a4-11e6-8dea-19df5dfa949b.png)

**Comment by DaleLaw** [comment]
Notes to people who want to know where to modify in morris.js

1. Search for **Donut.prototype.select** in Morris.js
2. Add **this.fire('selected', a, this.data[a]** in the function
3. Append Morris.Donut({ ... })**.on('selected' , function(i , row){ ... })**
4. Boom! Done!
