### ISSUE TITLE
Chart is not showing last value of X-lables.

### ISSUE THREAD

**Issue by dikshajiwane** [morrisjs/morris.js#707]
Hi,
Here is my screen shot of line chart. It is not showing last value of x-lables. What to do if I want to show last value.
![skill_history_error](https://cloud.githubusercontent.com/assets/25840600/23449801/039289ee-fe7e-11e6-851c-cbbe53ca7998.png)

**Comment by jayharland** [comment]
Same issue here.

**Comment by SrideviYerneni** [comment]
How did you get 'Skill levels' and 'Dates' on y-axis and x-axis?
