### ISSUE TITLE
Line chart overlapping data points, offset?

### ISSUE THREAD

**Issue by Rappies** [morrisjs/morris.js#747]
Hello,

I've been plotting multiple lines in 1 chart which works perfectly. In my specific case the lines tend to overlap for long periods of time, which makes it only distinguishable when you hover over a datapoint. I've been trying to find a way to slightly offset the lines only in the graph (so the data is still the same).

Situation:
![image](https://user-images.githubusercontent.com/35685892/35213800-2932bede-ff5f-11e7-9b0c-2031f587708b.png)

Wanted:
![image](https://user-images.githubusercontent.com/35685892/35213972-d8e937c2-ff5f-11e7-8635-bf8cd68b7468.png)

Is there a way to achieve this without adjusting the source data (not an option)?

Thanks!

**Comment by pierresh** [comment]
Hello,

That is possible only if you modify a bit morris.js. Indeed you need to check if the computed values that are in the _y[] -these are the Y axis coords of the points- are repeated or not before the paths are generated. I just made some tests, the following lines should do the job. Remark: the offset probably need to be adjusted, for me 3px seems fine

````    Line.prototype.calc = function() {
      this.calcPoints();
      _ref = this.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        for (_j = 0, _len2 = this.options.ykeys.length; _j < _len2; _j++) {
          var count = 0;
          for(var k = 0; k < _ref[_i]._y.length; ++k){
              if(_ref[_i]._y[k] == _ref[_i]._y[_j])
                  count++;
          }
          if (count > 1) {
            _ref[_i]._y[_j] = _ref[_i]._y[_j] - 3; // Adjust the 3 to the value that match with the offset you want
          }
        }
      }
      return this.generatePaths();
    };````

**Comment by Rappies** [comment]
Thanks for the reply!
I'm going to try it out.

**Comment by Rappies** [comment]
This is a very good start!

few issues: the normally empty datapoints jump up, and the normally invisible mousehoover points get visible:

![image](https://user-images.githubusercontent.com/35685892/35226924-f01fee36-ff8c-11e7-91f9-f577f875dc35.png)

**Comment by pierresh** [comment]
For the datapoint jump up: I cannot reproduce the problem you described, may be you can give me the dataset of your example, so that I could investigate more?

For the mousehoover: the modification I provided above should not have any influence on it

**Comment by Rappies** [comment]
Thanks for the help!

I've been trying to fix it without any succes. 
The problem might be that the data contains null, since the datapoint has to be ommited from the graph (not show 0). These is the way I fill it and the datapoint set.

![image](https://user-images.githubusercontent.com/35685892/35263980-35596106-001b-11e8-8671-a9708cd54b21.png)

**Comment by Rappies** [comment]
I got it to work with 2 parallel lines, but it doesnt seem to work with 2+ on the same point.
Trying to work around it.

**Comment by pierresh** [comment]
Yes, you are right, the offset should depend on the number of count actually. You can try with this:
````
if (count > 1) {
     _ref[_i]._y[_j] = _ref[_i]._y[_j] - 3 * (count - 1);
}

**Comment by Rappies** [comment]
Thanks for the help.
This works perfectly!
