### ISSUE TITLE
Set currently selected (hovered) pointSize

### ISSUE THREAD

**Issue by Demitrius** [morrisjs/morris.js#749]
Does it possible set hovered point size?

**Comment by pierresh** [comment]
Unfortunately the size of the hovered point (actually the difference of standard point and hovered point) is hard coded. If you want to modify it, just change the default value (3px) to the size you want in morris.js on line 1276:

`r: this.pointSizeForSeries(index) + 3`

**Comment by Demitrius** [comment]
Thanks, its help me.
