### ISSUE TITLE
Repeated values on X-axis, parseTime: false not working

### ISSUE THREAD

**Issue by SrideviYerneni** [morrisjs/morris.js#753]
Hi, I'm trying to display line chart with daily analytics. But the dates on X- axis seem to be repeating when there are few days.  
Here is the code for line chart: 
````
 new Morris.Line({
  element: 'chart',
  data: [ @foreach($Data as $data)
        { date: '{{$data['date']}}', value: {{$data['diff']}}},
        @endforeach
    ],
   xkey: ['date'],
   xLabelFormat: function(date) {
      return date.getFullYear() + '/' + (date.getMonth()+1)+ '/' + date.getDate(); 
      },
   xLabelAngle : 50,
   ykeys: ['value'],
   labels: ['Value'],
   resize: true,
   smooth: true,
   lineColors: ['#9ec628'],
  dateFormat: function(date) {
  date = new Date(date);
        return date.getFullYear()+ '/' + (date.getMonth()+1)+ '/' + date.getDate(); 
            },
          
}); 
````

**I tried using parseTime: false and it is not working.**
![screen shot 2018-02-22 at 7 49 36 am](https://user-images.githubusercontent.com/24527029/36541885-ffa4b79e-17a4-11e8-8533-674009153fa3.png)

**Comment by pierresh** [comment]
Could you please give us your dataset ? Thus we could reproduce your problem and check what is wrong.

**Comment by SrideviYerneni** [comment]
Sure. 
```
data: [
                { date: '2018-02-16', value: 5 },
                { date: '2018-02-17', value: 10 },
                { date: '2018-02-18', value: 15 },
                { date: '2018-02-19', value: 10 },
                { date: '2018-02-20', value: 20 }
              ]
```

**Comment by pierresh** [comment]
You are right, the values are repeated if the chart is very wide. However, if you remove the function _xLabelFormat_ and set _parseTime_ to **false**, it works well.

Here is what I get with this configuration:
```
Morris.Area({
  element: 'chart',
  data: [
    { date: '2018-02-16', value: 5 },
    { date: '2018-02-17', value: 10 },
    { date: '2018-02-18', value: 15 },
    { date: '2018-02-19', value: 10 },
    { date: '2018-02-20', value: 20 }
  ],
  xkey: ['date'],
  xLabelAngle : 50,
  ykeys: ['value'],
  labels: ['Value'],
  resize: true,
  smooth: true,
  parseTime: false,
  lineColors: ['#9ec628'],
  dateFormat: function(date) {
    date = new Date(date);
    return date.getFullYear()+ '/' + (date.getMonth()+1)+ '/' + date.getDate(); 
  },
});
```
![image](https://user-images.githubusercontent.com/7520095/36597987-bd15fc70-18e5-11e8-9cf0-9e47f9ef1f49.png)

**Comment by pierresh** [comment]
Another solution is just to add the option `xLabels: 'day',` to your config, and it would display only 1 value in x-axis per day. I just found that option in the documentation http://morrisjs.github.io/morris.js/lines.html

**Comment by SrideviYerneni** [comment]
Thank you. It works well
