### ISSUE TITLE
Creating simple area chart with color change inside the area

### ISSUE THREAD

**Issue by darsadask** [morrisjs/morris.js#761]
![capture](https://user-images.githubusercontent.com/5181183/38926841-9cc756a6-4321-11e8-99e0-cf9064c9f3f1.JPG)

i want to display area chart like this, the color of the area is chaged when moving away from x axis.
And also can i created pie chart using morris chart.

**Comment by schirrel** [comment]
Unfortunatelly morris dont have pie chart.
And as far as i know there's no built in funcion for it, and morris is not maintened latelly, but you can also try to code it itself, the core for morris is fairly simple. You u want i may help you

**Comment by schirrel** [comment]
@darsadask you can use @pierresh fork who also is AWESOME
https://pierresh.github.io/morris.js/
