### ISSUE TITLE
Drawing straight horizontal line

### ISSUE THREAD

**Issue by terhoraj** [morrisjs/morris.js#767]
Is it possible to draw horizontal line in a way as my example image is showing? I am looking to show limits on a specific value.

![line](https://user-images.githubusercontent.com/19226200/42944201-b2878f80-8b6d-11e8-8ef0-647fed71bbf1.PNG)

**Comment by pierresh** [comment]
Hello,

Yes, you can set the goals in the options of the chart. You can read more about it in the help: http://morrisjs.github.io/morris.js/lines.html

**Comment by terhoraj** [comment]
I seriously need glasses since I didn't notice this. So it's called "goals"

Oh yeah and thank you very much for fast response and help!
