### ISSUE TITLE
Weird Behavior (bundled with Twitter Bootstrap).

### ISSUE THREAD

**Issue by jmesserer** [morrisjs/morris.js#77]
1st - Thanks for making this library available ... it's awesome!

I'm seeing some weird behavior when I put the charts into a tabbed interface. The labels on the donut chart are off and the line graphs x-axis seems to get truncated. I started digging into but haven't figured it out yet. I'm using Twitter Bootstrap for the UI framework and the tabbed interface. So - the charts render fine if they are on the active tab when the page loads but they are weird if they are on a non-active tab after page load.

I tried switching tabs with JS after the page load but that didn't help.

You can see an example @ http://9rconsulting.com/weird-chart-behavior/

Any thoughts/insight are appreciated!

Thanks =~ Jeremiah

**Comment by matisoffn** [comment]
I'm having this issue as well.  I've done what @oesmith suggested.

Prior to implementing the fix that @oesmith suggested, the graph wasn't showing at all.  After doing so, the graph now shows but doesn't take up the full container and doesn't show all bars (as it is a bar graph).

This is the code I have:

```javascript
          $(document).on('shown.bs.tab', 'a[data-toggle="tab"]', function(e) {
            graphs.map(function(graph) {
              graph.redraw();
            });
          });
```
