### ISSUE TITLE
Morris Donut Chart label is showing undefined error

### ISSUE THREAD

**Issue by ShajahanKP** [morrisjs/morris.js#778]
Dear Friends,

I am using Morris Donut chart to display the progress. I am getting the count of status correctly. But instead of Label it is showing undefined in the donut chart.
![image](https://user-images.githubusercontent.com/48618703/54473817-61cf1900-47f6-11e9-8f07-5dc43fc9de77.png)

`var dtData = _.groupBy(jsonData, "status");
            var keys = [];
            keys = Object.keys(dtData);
            alert(keys);

           
            dtArr = [];

            for (var n = 0; n < keys.length; n++) {

                dtArr.push({
                    name: '' + keys[n] + '', value: '' + dtData[keys[n]].length + '',

                });

            } `

` Morris.Donut({
                element: 'dashboard-donut-8',
                data: dtArr,
                label: 'name',
                value: 'value',
                colors: ['#33414E', '#E04B4A', '#1caf9a', '#95b75d'],
                resize: true
            });`

I am getting the value correctly. But getting as **undefined** for label.

Please help me on this

**Comment by pierresh** [comment]
You should use the key **label** instead of **name**

`label: '' + keys[n] + '', value: '' + dtData[keys[n]].length + '',`

**Comment by ShajahanKP** [comment]
> You should use the key **label** instead of **name**
> 
> `label: '' + keys[n] + '', value: '' + dtData[keys[n]].length + '',`

I changed as shown below:

` for (var n = 0; n < keys.length; n++) {`
`dtArr.push({
                    label: '' + keys[n] + '', value: '' + dtData[keys[n]].length + '',

                });`
`} `
`Morris.Donut({`
`element: 'dashboard-donut-8',`
`data: dtArr,`
`label: 'label',`
`value: `'value',`
`colors: ['#33414E', '#E04B4A', '#1caf9a', '#95b75d'],`
`  resize: true`
`});`

                
Is the right way ??
Kindly suggest

**Comment by ShajahanKP** [comment]
> You should use the key **label** instead of **name**
> 
> `label: '' + keys[n] + '', value: '' + dtData[keys[n]].length + '',`

Thanks :+1: 

Works properly :100:
