### ISSUE TITLE
feature requested : combination chart or multiple chart with combined facility.

### ISSUE THREAD

**Issue by ankitkanojia** [morrisjs/morris.js#792]
Hello all the contributors and developers of Morris.js, First of all, You're doing a great job, Keep it Up!!!

I just want to know whether you're going to develop a combination chart or not, personally, I use your chart library but I required a combination of the chart but I can not have any option to develop it.

So can you please provide such a feature with a combination of multiple charts. or guide me.

Thank you.

**Comment by pierresh** [comment]
If you mean combining bar chart and line chart together, you need to use [my fork](https://pierresh.github.io/morris.js/). You can then create a bar chart, and with the option **nbYkeys2** you can set how many series are displayed as lines on the second right axis.

**Comment by ankitkanojia** [comment]
Thank you @pierresh, I get what I want from your shared URL. Thank you so much.
